apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.Configmap.name }}
  labels:
    spring.cloud.kubernetes.config: {{ .Values.Configmap.label.kubernetes.config }}
  annotations:
    spring.cloud.kubernetes.configmap.apps: {{ .Values.Configmap.annotation.kubernetes.apps }}
data:
  application.properties: |-
    spring.application.name={{ .Values.Configmap.application.properties.name }}
    rest.service.test.value={{ .Values.Configmap.application.properties.rest.value }}
    management.endpoints.web.exposure.include={{ .Values.Configmap.application.properties.management.endpoints }}
